# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  #config.vm.box = "hashicorp/precise64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 4567

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.66.100"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    #vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    #vb.customize ["modifyvm", :id, "--ioapic", "on"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "install_base_system.sh"
  # config.vm.provision "shell", path: "install_csf.sh"
  config.vm.provision "shell", path: "install_mysql.sh"
  config.vm.provision "shell", path: "install_nginx.sh"
  config.vm.provision "shell", path: "install_phpfpm.sh"
  config.vm.provision "shell", path: "install_redis.sh"
  config.vm.provision "shell", path: "create_snakeoil_certs.sh"
  config.vm.provision "shell", path: "create_dh_key.sh"
  config.vm.provision "shell", path: "install_unbound.sh"
  config.vm.provision "shell", path: "install_wordpress.sh"
  # config.vm.provision "shell", path: "install_owncloud.sh"
  # config.vm.provision "shell", path: "install_nextcloud.sh"
  # config.vm.provision "shell", path: "install_phpmyadmin.sh"
  # config.vm.provision "shell", path: "install_webmail_lite.sh"
end
